M48
; DRILL file {KiCad 7.0.1-3b83917a11~172~ubuntu22.04.1} date Wed 12 Apr 2023 03:56:53 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-12T15:56:53-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-3b83917a11~172~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0469
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0472
%
G90
G05
T1
X7.1Y-2.7
X7.2Y-2.7
T2
X6.7Y-3.3
X6.7Y-3.4
X6.7Y-3.7
X6.7Y-3.8
T3
X7.1Y-3.0098
X7.1Y-4.2098
X7.9Y-2.6
X7.9Y-4.6
T0
M30
